### ISSUE TITLE
Implement Base64 Analyzer

### ISSUE THREAD

**Issue by d-Rickyy-b** [d-Rickyy-b/pastepwn#120]
There should be a new analyzer to find pastes which (probably) contain base64 encoded texts.

To solve this issue there needs to be a new analyzer added in the [analyzers directory](https://github.com/d-Rickyy-b/pastepwn/tree/master/pastepwn/analyzers). The analyzer must follow the example of the other analyzers in this directory. Don't forget to add the analyzer to the [analyzer package file](https://github.com/d-Rickyy-b/pastepwn/blob/master/pastepwn/analyzers/__init__.py).

The most simple example for such an analyzer is the [AlwaysTrueAnalyzer](https://github.com/d-Rickyy-b/pastepwn/blob/master/pastepwn/analyzers/alwaystrueanalyzer.py) which always returns True.

This analyzer should extend the `RegexAnalyzer`. I expect unit tests to be part of the PR so that you can show off that the given regex works. Please add at least 5 positive and 5 negative tests. Creating uint tests is not hard - see [this unit test file](https://github.com/d-Rickyy-b/pastepwn/blob/master/pastepwn/analyzers/tests/steamkeyanalyzer_test.py) for example. If there are questions, don't hesitate to contact me.

Via a quick Google search I found the following regex which you could use!

`^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$` - source: https://stackoverflow.com/questions/475074/regex-to-parse-or-validate-base64-data

**Comment by martin-bucinskas** [comment]
Looks interesting, will check this out today and submit a PR if you don't mind!

**Comment by d-Rickyy-b** [comment]
Sounds good :)

**Comment by d-Rickyy-b** [comment]
Fixed in #127
