### ISSUE TITLE
Implement Slack Token Analyzer

### ISSUE THREAD

**Issue by d-Rickyy-b** [d-Rickyy-b/pastepwn#128]
There should be a new analyzer to find pastes which (probably) contain slack tokens.

To solve this issue there needs to be a new analyzer added in the [analyzers directory](https://github.com/d-Rickyy-b/pastepwn/tree/master/pastepwn/analyzers). The analyzer must follow the example of the other analyzers in this directory. Don't forget to add the analyzer to the [analyzer package file](https://github.com/d-Rickyy-b/pastepwn/blob/master/pastepwn/analyzers/__init__.py).

The most simple example for such an analyzer is the [AlwaysTrueAnalyzer](https://github.com/d-Rickyy-b/pastepwn/blob/master/pastepwn/analyzers/alwaystrueanalyzer.py) which always returns True.

This analyzer should extend the `RegexAnalyzer`. I expect unit tests to be part of the PR so that you can show off that the given regex works. Please add at least 5 positive and 5 negative tests. Creating uint tests is not hard - see [this unit test file](https://github.com/d-Rickyy-b/pastepwn/blob/master/pastepwn/analyzers/tests/steamkeyanalyzer_test.py) for example. If there are questions, don't hesitate to contact me.

You can use the regex used in the shhgit repository: https://github.com/eth0izzle/shhgit/blob/f9b4febcd6ec6c1d509b28efbad6dc1ca9d17837/config.yaml#L351-L353

**Comment by dmoneyballer** [comment]
I'll take a stab at this one

**Comment by dmoneyballer** [comment]
Are these the kind of slack tokens we are trying to match?
https://api.slack.com/docs/token-types

**Comment by dmoneyballer** [comment]
I created a pull request #133
