### ISSUE TITLE
[SQLite] Create database file in current directory throws error

### ISSUE THREAD

**Issue by DanBenHa** [d-Rickyy-b/pastepwn#155]
**Description**
Creating new SQLite database fails if dbpath does not contain subfolder or absolute path. 

**Steps To Reproduce**
```
from pastepwn.database import sqlitedb

db = sqlitedb.SQLiteDB()
```

Gives this error:

```
     18         if not os.path.exists(os.path.dirname(dbpath)):
     19             # If not, create the path and the file
---> 20             os.mkdir(os.path.dirname(dbpath))
     21             open(self.dbpath, "a").close()
     22 

FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Expected behavior**
Create database file in current directory.

**Comment by d-Rickyy-b** [comment]
Thanks for finding.
The default parameter for the dbpath should also be adjusted. No idea how this ever worked.

https://github.com/d-Rickyy-b/pastepwn/blob/master/pastepwn/database/sqlitedb.py#L11

**Comment by DanBenHa** [comment]
What should the default path be?

**Comment by d-Rickyy-b** [comment]
It should be the current working directory + `pastepwn.db`.

I think there should be a check if the path `is None or ""` and if true, then we can set it with:
```
db_dir = os.path.dirname(os.path.abspath(__file__))
db_path = os.path.join(db_dir, "pastepwn.db")
```
