### ISSUE TITLE
Many DNS requests for domain api.ipify.org

### ISSUE THREAD

**Issue by DaRuudii** [d-Rickyy-b/pastepwn#161]
**Description**
pastepwn creates many DNS requests for the domain api.ipify.org while running. There are aroung 80 requests per 10 minutes as seen in the screenshots.

https://github.com/d-Rickyy-b/pastepwn/blob/master/pastepwn/core/pastepwn.py#L37

**Screenshots**

![image](https://user-images.githubusercontent.com/8517764/68697606-79c28c80-057f-11ea-821d-65a3829d2ace.png)
![image](https://user-images.githubusercontent.com/8517764/68697628-83e48b00-057f-11ea-883f-9b389b4dea63.png)
![image](https://user-images.githubusercontent.com/8517764/68697645-8c3cc600-057f-11ea-8fcd-c161134e3e68.png)
![image](https://user-images.githubusercontent.com/8517764/68697815-e3db3180-057f-11ea-9cad-a1cb24f69eb4.png)

**Comment by d-Rickyy-b** [comment]
Great catch. Just two questions:

1) Which pastepwn version do you use?
2) What does your "config" file (where you include pastepwn) look like?

**Comment by d-Rickyy-b** [comment]
It looks like pastepwn is restarting over and over and over again (every 7 seconds). It does not even start to connect to pastebin which is strange. Also no error is logged. 

Could you try updating to v1.1.0 ?

**Comment by DaRuudii** [comment]
Problem was an analyzer which was not implemented but then called upon. This led to a crash of pastepwn but because I configured it as a service to restart automatically, it restarted and failed again.
