### ISSUE TITLE
New word analyzer that matches full words

### ISSUE THREAD

**Issue by d-Rickyy-b** [d-Rickyy-b/pastepwn#164]
Optionally this can be implemented in the already existing analyzer.

**Comment by abc22413** [comment]
Could I find out what such a word analyzer entails? Is it similar to a conventional word search function?

**Comment by d-Rickyy-b** [comment]
Hi @abc22413 - sorry for the long wait. Currently when creating a [WordAnalyzer](https://github.com/d-Rickyy-b/pastepwn/blob/master/pastepwn/analyzers/wordanalyzer.py) and passing "foo", it will also match occurrences of "foobar" or "barfoo". My thought was that we could create another analyzer that only matches "foo" standing alone. E.g. it would match "test foo bar" or "test foo.". This might be possible with regex and the [word boundary operator \b](https://www.regular-expressions.info/wordboundaries.html). Translated to regex this could mean `\bsearchword\b` I guess.

**Comment by Pooja269** [comment]
Hi.. Can I work on this issue?

**Comment by d-Rickyy-b** [comment]
Hi @Pooja269, sure go ahead. Ping me when you need anything.

**Comment by d-Rickyy-b** [comment]
Added in #194 - not merged into master yet.
