### ISSUE TITLE
New Analyzer: Base64AsciiAnalyzer

### ISSUE THREAD

**Issue by d-Rickyy-b** [d-Rickyy-b/pastepwn#166]
Implement a new analyzer that subclasses Base64Analyzer and only returns True if the found base64 decodes to valid ascii characters.

We can overwrite the verify method and call `super().verify(results)` before doing our base64 ascii decoding.

**Comment by jonahrosenblum** [comment]
I'd like to take a shot at this.

**Comment by d-Rickyy-b** [comment]
Thanks, I'd be very happy about that. If you have any questions, feel free to ask!

**Comment by jonahrosenblum** [comment]
Hey, I tried to send you a message on telegram but I'm not sure if it reached you. I have some questions about getting the databases to work, test cases, etc. if you don't mind.

**Comment by d-Rickyy-b** [comment]
Hi there, I did not receive any message so far. You sent your message the right way? https://t.me/d_Rickyy_b is my username :)

**Comment by jonahrosenblum** [comment]
I believe it sent correctly this time, please let me know if you still did not receive anything.
