### ISSUE TITLE
Create contributing guidelines

### ISSUE THREAD

**Issue by d-Rickyy-b** [d-Rickyy-b/pastepwn#173]
The guidelines should describe how you can contribute to this project.

References:
https://www.conventionalcommits.org/en/v1.0.0-beta.4/
https://keepachangelog.com/en/1.0.0/
https://semver.org/

**Comment by borng-osu** [comment]
Ok, thanks! I'll see what I can do. I'm pretty familiar with contributing guidelines from researching other OSS projects, so I might use some of the ones I prefer as jumping off points.

**Comment by borng-osu** [comment]
So glad I could help! Thanks for the positive feedback!

**Comment by d-Rickyy-b** [comment]
Fixed in https://github.com/d-Rickyy-b/pastepwn/pull/219
