### ISSUE TITLE
pastepwn.core.actionhandler - ERROR - While performing the action 'EmailAction' the following exception occurred: ''Paste' object has no attribute 'template''

### ISSUE THREAD

**Issue by zespirit** [d-Rickyy-b/pastepwn#175]
Hi, 

Im getting this error while running main.py

**pastepwn.core.actionhandler - ERROR - While performing the action 'EmailAction' the following exception occurred: ''Paste' object has no attribute 'template''**

i tried to swicth from telegram to email action in main.py

```
# -*- coding: utf-8 -*-

import logging.handlers
import os

from pastepwn import PastePwn
from pastepwn.actions import EmailAction
from pastepwn.analyzers import MailAnalyzer, WordAnalyzer
from pastepwn.database import MysqlDB

# Generic action to send Telegram messages on new matched pastes
telegram_action = EmailAction
mail_analyzer = MailAnalyzer(telegram_action)
pastepwn.add_analyzer(mail_analyzer)
```

Please help me out as im loving the logging feature

**Comment by d-Rickyy-b** [comment]
Hi there, could you please tell me which version of pastepwn you are using?
You can check with `pip freeze`.

Also it would be nice if you could send a full error log, not just a single line. That way I might get an important hint where the issue is coming from.

Thank you 😃

**Comment by zespirit** [comment]
pastepwn==1.2.0
i installed it using pip3 install pastepwn
logging to the mysql DB works excellent.
just the other problem im having i cant seem to figure out how to solve.
thank you for getting back to me so quickly, support is amazing :-)

**Comment by zespirit** [comment]
main.py
# -*- coding: utf-8 -*-

import logging.handlers
import os

from pastepwn import PastePwn
from pastepwn.actions import EmailAction
from pastepwn.analyzers import MailAnalyzer, WordAnalyzer
from pastepwn.database import MysqlDB

# Setting up the logging
logdir_path = os.path.dirname(os.path.abspath(__file__))
logfile_path = os.path.join(logdir_path, "logs", "pastepwn.log")

if not os.path.exists(os.path.join(logdir_path, "logs")):
    os.makedirs(os.path.join(logdir_path, "logs"))

logfile_handler = logging.handlers.WatchedFileHandler(logfile_path, "a", "utf-8")

logger = logging.getLogger(__name__)
logging.basicConfig(format="%(asctime)s - %(name)s - %(levelname)s - %(message)s", level=logging.INFO, handlers=[logfile_handler, logging.StreamHandler()])

# Framework code
#database = MongoDB(ip="192.168.240.128")
database = MysqlDB(ip="localhost", port=3306, username="MYUSername", password="MYPAssword")

pastepwn = PastePwn(database)

# Generic action to send Telegram messages on new matched pastes
telegram_action = EmailAction

mail_analyzer = MailAnalyzer(telegram_action)
#premium_analyzer = WordAnalyzer(telegram_action, "premium")

pastepwn.add_analyzer(mail_analyzer)
#pastepwn.add_analyzer(premium_analyzer)

pastepwn.start()


__________________________________________________________________________________________


emailaction.py

# -*- coding: utf-8 -*-
import re
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from .basicaction import BasicAction
from pastepwn.util import TemplatingEngine


class EmailAction(BasicAction):
    """This action takes a username, password, receiver mail address,
    hostname, port and when executed sends out an e-mail to the receiver
    containing the paste"""
    name = "EmailAction"

    def __init__(self, username, password, receiver, hostname, port=465, template=None):
        super().__init__()
        mail_regex = r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)"
        if username is None or not re.match(mail_regex, username):
            raise ValueError('Invalid username !')
        else:
            self.username = im@home.com
        if receiver is None or not re.match(mail_regex, receiver):
            raise ValueError('Invalid reciever address !')
        else:
            self.receiver = my@email.com
        self.password = mypassword
        self.hostname = mail.myserver.com
        self.port = 25
        self.template = template

#        if self.template is None:
#            self.template = "New paste matched by analyzer '{analyzer_name}' - Link: {url}"

    def perform(self, paste, analyzer_name=None, matches=None):
        """
        Sends an email to the specified receiver with the paste's content
        :param paste: The paste passed by the ActionHandler
        :param analyzer_name: The name of the analyzer which matched the paste
        :param matches: A list of matches, on which the analyzer matched on
        :return: None
        """
        text = TemplatingEngine.fill_template(paste, analyzer_name, template_string=self.template, matches=matches)

        email = MIMEMultipart()
        email['From'] = self.username
        email['To'] = self.receiver
        email['Subject'] = 'Paste matched by pastepwn via analyzer "{}"'.format(analyzer_name)
        email.attach(MIMEText(text, 'plain'))

        # TODO there should be a way to use starttls - check https://realpython.com/python-send-email/
        with smtplib.SMTP_SSL(self.hostname, self.port) as smtp:
            smtp.login(self.username, self.password)
            text = email.as_string()
            smtp.sendmail(self.username, self.receiver, text)

_________________________________________________________________________________

**Comment by zespirit** [comment]
this is what is shown after i run the script

2020-02-27 18:34:12,614 - pastepwn.util.request - INFO - Using the following custom proxies: None
2020-02-27 18:34:12,616 - pastepwn.util.request - INFO - Using the following system proxies: {}
2020-02-27 18:34:12,795 - pastepwn.core.pastepwn - INFO - Your public IP is 220.200.107.147
2020-02-27 18:34:12,795 - pastepwn.core.pastepwn - INFO - Database provided! Storing pastes in there.
2020-02-27 18:34:43,059 - pastepwn.core.actionhandler - ERROR - While performing the action 'EmailAction' the following exception occurred: ''Paste' object has no attribute 'template''

**Comment by d-Rickyy-b** [comment]
Thanks for the details @zespirit - I was able to reproduce your issue.

It is because you did not instantiate `EmailAction`.

You need to create an instance of the EmailAction and pass it your email address and password, the receiver of the mail and the mail server's hostname. Use the following code and insert your data. That should be working:

main.py
```
# -*- coding: utf-8 -*-

import logging.handlers
import os

from pastepwn import PastePwn
from pastepwn.actions import EmailAction
from pastepwn.analyzers import MailAnalyzer, WordAnalyzer
from pastepwn.database import MysqlDB

# You need to replace 'me@gmail.com' with your sender mail address, 
# "myPassword" with the password of that address,
# the receiver (me@example.com) with the receiver of the mail
# and the hostname (smtp.gmail.com) with the SMTP server hostname of your mail provider.

email_action = EmailAction(username="me@gmail.com", password="myPassword", receiver="me@example.com", hostname="smtp.gmail.com")
mail_analyzer = MailAnalyzer(email_action)
pastepwn.add_analyzer(mail_analyzer)
```

If you entered your personal information, an email will be sent on each matched paste.
Please let me know if you are having further questions or if you need further support!

**Comment by zespirit** [comment]
Traceback (most recent call last):
  File "main2.py", line 18, in <module>
    pastepwn.add_analyzer(mail_analyzer)
NameError: name 'pastepwn' is not defined

is what i get back....

**Comment by zespirit** [comment]
we can do an easier one if you want
like the irc...it produces the same results

**Comment by d-Rickyy-b** [comment]
Yes, I removed some of the code for giving a minimal example. This is the full code for your main.py - that should work when you use the correct username/password/hostname.

```
# -*- coding: utf-8 -*-

import logging.handlers
import os

from pastepwn import PastePwn
from pastepwn.actions import EmailAction
from pastepwn.analyzers import MailAnalyzer, WordAnalyzer
from pastepwn.database import MysqlDB

# Setting up the logging
logdir_path = os.path.dirname(os.path.abspath(__file__))
logfile_path = os.path.join(logdir_path, "logs", "pastepwn.log")

if not os.path.exists(os.path.join(logdir_path, "logs")):
    os.makedirs(os.path.join(logdir_path, "logs"))

logfile_handler = logging.handlers.WatchedFileHandler(logfile_path, "a", "utf-8")

logger = logging.getLogger(__name__)
logging.basicConfig(format="%(asctime)s - %(name)s - %(levelname)s - %(message)s", level=logging.INFO, handlers=[logfile_handler, logging.StreamHandler()])

# Framework code
database = MysqlDB(ip="localhost", port=3306, username="MYUSername", password="MYPAssword")

pastepwn = PastePwn(database)

# You need to replace 'me@gmail.com' with your sender mail address, 
# "myPassword" with the password of that address,
# the receiver (me@example.com) with the receiver of the mail
# and the hostname (smtp.gmail.com) with the SMTP server hostname of your mail provider.

email_action = EmailAction(username="me@gmail.com", password="myPassword", receiver="me@example.com", hostname="smtp.gmail.com")
mail_analyzer = MailAnalyzer(email_action)
pastepwn.add_analyzer(mail_analyzer)

mail_analyzer = MailAnalyzer(email_action)

pastepwn.add_analyzer(mail_analyzer)

pastepwn.start()
```

**Comment by zespirit** [comment]
trying now...one moment

**Comment by zespirit** [comment]
Beautifull....this is wonderfull.
May i ask one last question to orient myself with the rest of the script.
can i use the email and irc actions at the same time?
can you tell me what to add to get irc to work also.
i am also willing to send a donation for all your time.
your support was amazing.

**Comment by zespirit** [comment]
example
i added
from pastepwn.actions import EmailAction, IrcAction


irc_action = IrcAction(server="us.undernet.org", channel="#0daywarezs", port="6667", nick="pastepwns69")
irc_analyzer = MailAnalyzer(irc_action)
pastepwn.add_analyzer(irc_analyzer)

and got this error

pastepwn.core.actionhandler - ERROR - While performing the action 'IrcAction' the following exception occurred: 'an integer is required (got type str)'

**Comment by d-Rickyy-b** [comment]
> 
> 
> example
> i added
> from pastepwn.actions import EmailAction, IrcAction
> 
> irc_action = IrcAction(server="us.undernet.org", channel="#0daywarezs", port="6667", nick="pastepwns69")
> irc_analyzer = MailAnalyzer(irc_action)
> pastepwn.add_analyzer(irc_analyzer)
> 
> and got this error
> 
> pastepwn.core.actionhandler - ERROR - While performing the action 'IrcAction' the following exception occurred: 'an integer is required (got type str)'

The port must be an integer. Try
```
irc_action = IrcAction(server="us.undernet.org", channel="#0daywarezs", port=6667, nick="pastepwns69")
```
(see that the quotes around the port number are gone now)

**Comment by zespirit** [comment]
ok that error is gone and a new one showed up
pastepwn.core.actionhandler - ERROR - While performing the action 'IrcAction' the following exception occurred: '[Errno 106] Transport endpoint is already connected'.

so just to be clear i have email action before irc action, emails are showing up perfectly, irc is giving this error and not connecting or pasting to the room

pastepwn.core.actionhandler - ERROR - While performing the action 'IrcAction' the following exception occurred: '[Errno 106] Transport endpoint is already connected'

**Comment by d-Rickyy-b** [comment]
> Beautifull....this is wonderfull.
> May i ask one last question to orient myself with the rest of the script.
> can i use the email and irc actions at the same time?

Yes, you can :)

> can you tell me what to add to get irc to work also.
1. To your imports (top of the file) add:
`from pastepwn.actions import IrcAction`
2. Then you need to create an instance of it and configure it (servername, nick, port, etc.) and add it to your code

> also can i run multiple analysers at a time.

Yes, you can.

> can you provide an example please

I quickly wrote a gist for that. It's easier:
https://gist.github.com/d-Rickyy-b/e83dab86b812a3cacc112d1851223de2

> i am also willing to send a donation for all your time.
> your support was amazing.

Glad I could help you :)

**Comment by d-Rickyy-b** [comment]
> ok that error is gone and a new one showed up
> pastepwn.core.actionhandler - ERROR - While performing the action 'IrcAction' the following exception occurred: '[Errno 106] Transport endpoint is already connected'.
> 
> so just to be clear i have email action before irc action, emails are showing up perfectly, irc is giving this error and not connecting or pasting to the room
> 
> pastepwn.core.actionhandler - ERROR - While performing the action 'IrcAction' the following exception occurred: '[Errno 106] Transport endpoint is already connected'

I will have a look at that tomorrow. It's quite late where I live and I should really be in bed right now 😋 . Let me know if you are able to fix the issue yourself. I haven't had to do a lot of testing for the IRC Action yet.

**Comment by zespirit** [comment]
Thanks for your help msg me where i can send some funds for your time and work.
your project rocks...

**Comment by zespirit** [comment]
Hello friend i have not had any luck with the IRC module
#irc_action = IrcAction(server="dallas.tx.us.undernet.org", channel="#beginner", port=6667, nick="pastepwn")

try to connect here if you want since i have mirc installed i will be able to see whether or not you are connected.
i personally tested all of the analyzers and all work as expected except ipv4, it cant find the class for some reason. but aside of that, solid work here.

if we can figure out irc this would be golden

**Comment by d-Rickyy-b** [comment]
@zespirit could you create another issue for the IrcAction (with as much helpful information as possible) please? That way we can track it individually. Thank you!

**Comment by zespirit** [comment]
great. mark this one as closed

**Comment by d-Rickyy-b** [comment]
It will be closed automatically as soon as I merge the dev branch into master.
