### ISSUE TITLE
Please Add the pastebin title in the mail action to identify the kind of paste

### ISSUE THREAD

**Issue by zespirit** [d-Rickyy-b/pastepwn#178]
instead of 
Paste matched by pastepwn via analyzer "EmailPasswordPairAnalyzer"

would it be possible to add the pastebin title
Paste matched by pastepwn via analyzer "EmailPasswordPairAnalyzer + spotify"

**Comment by d-Rickyy-b** [comment]
You mean the title of the paste which was found? Or what exactly should be added?

The EmailPasswordPairAnalyzer does not only find Spotify email/password combos.

**Comment by zespirit** [comment]
"EmailPasswordPairAnalyzer + Pastebin_Title"
could be a format. if the title is in there it makes it easier to identify what the combo list is for

**Comment by d-Rickyy-b** [comment]
@zespirit you might want to check out the templating capabilities of pastepwn:

https://github.com/d-Rickyy-b/pastepwn/wiki/Templating-in-actions

You can easily control what should be sent in the action. You don't need to rely on the defaults.

### Example
```
[...] 

template = "New paste matched by pastepwn via analyzer '${analyzer_name}' - Title: '${title}'`
telegram_action = TelegramAction(token="token", receiver="<receiver>", template=template)

[...]
```

If you have questions using this, feel free to ask again.

**Comment by d-Rickyy-b** [comment]
Hi @zespirit, did you manage to get this resolved? Then I'd close the issue.

**Comment by d-Rickyy-b** [comment]
Hi @zespirit - you didn't get back to me, so I am going to close this issue. If you still got questions, feel free to open another one.
