### ISSUE TITLE
Use listify for certain analyzers

### ISSUE THREAD

**Issue by d-Rickyy-b** [d-Rickyy-b/pastepwn#190]
I found that certain analyzers are still using their own "listify" code.

e.g. 

https://github.com/d-Rickyy-b/pastepwn/blob/9b2fee22857e54a5312fdb3d388b472a7d271c50/pastepwn/analyzers/wordanalyzer.py#L12-L17

This should not be the case.

**Comment by colinlcrawford** [comment]
@d-Rickyy-b should the words param always be of type List (or None)? or is there a different "listify" function you have in mind?

**Comment by d-Rickyy-b** [comment]
Hi @colinlcrawford, you can use the [listify](https://www.github.com/d-Rickyy-b/pastepwn/tree/master/pastepwn%2Futil%2Flistify.py) util function in analyzers whenever it should be possible to handle multiple inputs. I think it would be cool to handle multiple inputs for the whole word analyzer. Feel free to add this feature :)

Thanks in advance.

**Comment by colinlcrawford** [comment]
Hey @d-Rickyy-b , I did a scan of the analyzers and it looks like they've all been updated. The wordanalyzer ^ has been updated in dev and I made the update in my PR for the exactwordanalyzer as well

**Comment by d-Rickyy-b** [comment]
Fixed in https://github.com/d-Rickyy-b/pastepwn/commit/0f60fbace3943752a0b415dd97fabfa807981a56
