### ISSUE TITLE
Proxy settings for request

### ISSUE THREAD

**Issue by d-Rickyy-b** [d-Rickyy-b/pastepwn#20]
Currently it's not possible to run this framework behind a proxy

**Comment by d-Rickyy-b** [comment]
python-telegram-bot did a great job

https://github.com/python-telegram-bot/python-telegram-bot/blob/b9f56ca47900d92cd8757e72b392efef617997d3/telegram/utils/request.py#L127-L151

**Comment by d-Rickyy-b** [comment]
I guess this is an easy issue for people who already used **urllib3**. If you know how to add code to be able to use a proxy I would be very glad if you could help.

**Comment by StephenSorriaux** [comment]
Hi,

I could look into it. Is there a reason you are using **urllib3** and not **requests** (which is based on urllib3 too)?
By default, **requests** already use the environment variables HTTP_PROXY, HTTPS_PROXY to set the proxy. It is also possible to use a SOCKS proxy with the additionnal lib **requests[socks]**.

**Comment by d-Rickyy-b** [comment]
@StephenSorriaux thanks :)

I am not sure what the pros and cons of requests are. If you feel that requests is better, I would love to hear your reasons.

I thought that urllib3 might be more lightweight. But I am honest that I did not take much time for research of this topic.

**Comment by StephenSorriaux** [comment]
I think you are right about urllib3 being more lightweight. But there is no difference between the two in performance's terms. Also, I noticed urllib is recommanding **requests** as HTTP client (https://docs.python.org/3/library/urllib.request.html#module-urllib.request)

AFAICT, **requests** will give you right away some new features:

- proxy support using environment variables
- `.netrc` support, which would make HTTP auth easier using your framework
- if needed in the future, usage of Session for cookie persistence

I let you decide whether you want to stick with urllib3 or change to requests, I will submit a PR accordingly. :)

**Comment by d-Rickyy-b** [comment]
Feel free to use requests if it means less work (not re-inventing the wheel).

Thanks a lot :)
