### ISSUE TITLE
Syslog Action

### ISSUE THREAD

**Issue by DaRuudii** [d-Rickyy-b/pastepwn#21]
Implement an action which sends matched pastes to syslog.

**Comment by d-Rickyy-b** [comment]
This is a great issue for newcomers. Create a new class inheriting from the BasicAction (https://github.com/d-Rickyy-b/pastepwn/blob/master/actions/basicaction.py) and implement a method `perform`, which writes out the paste (as JSON?) to syslog

**Comment by d-Rickyy-b** [comment]
I am not sure if the logging module can be used (in a nice way) to log to syslog, or if an external package should be used. I am open to suggestions.

**Comment by heavysaturn** [comment]
the `logging` module has a `SysLogHandler` so this should be fairly simple to handle without external packages.

**Comment by d-Rickyy-b** [comment]
@heavysaturn is it possible to **only**  log the logs of one action to syslog then? Not that each debug output gets logged to syslog.

If that is possible it should be fairly simple and I'd be glad for any contribution - even if it's a 5 liner.

Greetings, Rico

**Comment by heavysaturn** [comment]
If I understand you correctly, you're asking whether we can use the `SysLogHandler` from `logging` without adding it to logging everywhere else in the system. The answer is yes, you can make a separate logger which will only be used in that particular class. I can pull request something quickly for you to illustrate.

**Comment by d-Rickyy-b** [comment]
I normally initialize the logging in the example file. There I add the handlers to the logging object. Now I only want the syslog action to log the specific pastes to the syslog only.

**Comment by heavysaturn** [comment]
yep, I see. Well, I would probably handle this particular logger within the SyslogAction class init then so the user doesn't have to configure that themselves. I threw together a quick example of this in #29

**Comment by d-Rickyy-b** [comment]
fixed in #29
