### ISSUE TITLE
Whitelisted IP Error not being caught

### ISSUE THREAD

**Issue by bellcha** [d-Rickyy-b/pastepwn#228]
**Description**
When trying to scrape from a Public IP that is not whitelisted by PasteBin, the error is not being caught properly.  Since the error is not being caught, the program continues to run instead of stopping.  

**Steps To Reproduce**
1. Have an account that is not a Pro Account.
2. Run the main.py example in the README.
3. When a request made to the PasteBin API URL, you receive a JSON parsing error since the regex (pastebin_error_pattern) in the PastbinScrapper class is not matching in the API request.

Error from Pastebin request response: Forbidden: YOUR IP: xxx.xx.xxx.xxx DOES NOT HAVE ACCESS. VISIT: https://pastebin.com/doc_scraping_api TO GET ACCESS!

Below is the error received to the console:

2023-04-01 13:40:44,193 - pastepwn.scraping.pastebin.pastebinscraper - ERROR - Expecting value: line 1 column 1 (char 0)

**Expected behavior**
Error to be handled and logged to the console and the program stops.

**Additional context**

I fixed the issue by editing the pastebin_error_pattern variable int he PastebinScraper class to the following:

pastebin_error_pattern = re.compile(r"^Forbidden: YOUR IP: ((\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3})|((([0-9A-Fa-f]{1,4}:){7})([0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){1,6}:)(([0-9A-Fa-f]{1,4}:){0,4})([0-9A-Fa-f]{1,4}))) DOES NOT HAVE ACCESS\.\s+VISIT: https://pastebin\.com/doc_scraping_api TO GET ACCESS!")

I can submit a pull request with this fix if needed.

**Comment by d-Rickyy-b** [comment]
Hi @bellcha and thank you for raising the issue. I changed the regex. It should work now.
