### ISSUE TITLE
RegexAnalyzers should return what they find, instead of just indicating whether or not they found it.

### ISSUE THREAD

**Issue by lemonsaurus** [d-Rickyy-b/pastepwn#27]
I'm not sure whether this idea is compatible with your current idea of how this tool should be used, but it strikes me as odd that the RegexAnalyzers simply report whether or not a match was found, rather than returning all the data they were able to match. 

For the PastebinURLAnalyzer I just made a pull request for, for example, I imagine it might be useful if you could feed it a number of pastes, and it could create some sort of dictionary which mapped the paste it had found a match on with a list of all URLs it was able to find.

That way, I could say "check out these 200 pastes and show me all the emails, pastebin urls, and bcrypt password hashes you find." 

Just an idea, of course. Would probably require a bit of a redesign of the way the analyzers are used, but would require minimal changes to the actual analyzers.

**Comment by d-Rickyy-b** [comment]
This is indeed a very nice idea I thought of several times. Currently this is not possible as you said, but it also bugs me a bit that you can't get the "match" of an analyzer.

I am currently using Telegram to get notified about matches. If the message would tell the exact match it would be way easier to skim the results for "useful" pastes. I like the idea and let the issue open for further ideas/suggestions/solutions.

**Comment by lpraz** [comment]
Would the analyzers, instead of returning True/False, return lists of matches including the text that was found and possibly the starting and ending line/column numbers for each match? The actions would need some reworking as well to pass on this information. This all seems doable with Python's regex, though.

**Comment by d-Rickyy-b** [comment]
Hi and thanks for your interest. Yes that would be able with python's regex. But I am not sure how I want to build the architecture for the actions in that case. I'll update this issue in the next days with further information.

**Comment by d-Rickyy-b** [comment]
I just started implementing this. I love the idea to be able to get the results right from the analyzers. Basically we need 3 things:
- analyzers must return a list of matches - fallback to boolean where list of matches is not applicable
- pastedispatcher must put the matches in tuple put in the action_queue
- actionhandler must pass the matches object to the actions
- actions must take the matches object as parameter

Should be done within a week or so.

**Comment by d-Rickyy-b** [comment]
This behaviour is pretty much implemented now in dev and only needs some testing and polishing.

For example: The templating engine I coded does not yet receive a copy of the matches, so it can't put in the matches by itself. I will try to fix this and have it running for a few days to see if everything works out as expected. Also I should document everything in the templating engine wiki page: https://github.com/d-Rickyy-b/pastepwn/wiki/Templating-in-actions

But for now every analyzer also returns its matches as a list and the actions receive these matches and could already use them.

**Comment by d-Rickyy-b** [comment]
Fixed in a0e862490382e72169a3d31a200535d6170ec8a1
