### ISSUE TITLE
Wrapper around various hash analyzers

### ISSUE THREAD

**Issue by d-Rickyy-b** [d-Rickyy-b/pastepwn#32]
Users might not want to calculate their password hashes beforehand and thus might want to be able to use a wrapper (analyzer) around various hash analyzers. They initialize that wrapper with their password in the clear. The wrapper generates the hashes on the fly and checks each paste against those hashes.

I am not sure if that's a good idea but I'll leave this here for now.

**Comment by d-Rickyy-b** [comment]
To add a bit more context:

The goal of this issue is to provide the user with a new [analyzer](https://github.com/d-Rickyy-b/pastepwn/tree/master/pastepwn/analyzers) or [utility](https://github.com/d-Rickyy-b/pastepwn/tree/master/pastepwn/util). From my perspective a new analyzer makes more sense, but if you come up with a nice solution, feel free to do whatever you like.

I think of a new class which gets initialized with the user's password. During initialization it calculates the password of the user with various hashing algorithms (md5, sha1, sha2, bcrypt, etc.) and saves them in a list. If using an analyzer subclass, you can match the paste in the match() function if it contains any of those hashes.

If you have questions, feel free to contact me or ask here.

**Comment by Zeroji** [comment]
I'll take this one! Actually seems pretty straightforward when using `hashlib`.

I feel like this would be most useful by taking a list of passwords as parameters, maybe checking that the argument isn't a string to prevent users from calling `func('pass')` instead of `func(['pass'])`.

Is it desirable to know which kind of hash was found? If not I'll simply extend RegexAnalyzer with careful pattern compiling.

Also, could you reformulate your last point? I'm not sure I understand it.

**Comment by d-Rickyy-b** [comment]
Hi there, you could probably also use a wordanalyzer for that, since we want to match exact ASCII text after generating the hashes.

I would prefer a way to be able to submit either a string or a list of strings (similar to the way analyzers can take an action or a list of actions).

I personally would not care much which kind of hash was found. To me it only seems important to know that a hashed password has been found.

Reformulated last point: many proper secured services use bcrypt as password hashing algorithm. You can't pre-calculate a bcrypt password and compare it since the bcrypt hashes always change. But you can parse a bcrypt hash and based on the salt and cost-factor you can calculate if the password is the same. But that should only be done if no additional imports are necessary.

**Comment by Zeroji** [comment]
I was going to use something like `\b(hash1|hash2|...)\b`, but I just noticed RegexAnalyzer doesn't allow passing `re.IGNORECASE` along with the pattern :(

Yes, that's what I meant - I looked at BasicAnalyzer and it does exactly what I thought.

Regarding bcrypt hashes, there's a pypi module for that, and we have `BcryptHashAnalyzer` (regex based) so either add it as optional dependency or drop it.

**Comment by d-Rickyy-b** [comment]
True, I should improve the regexanalyzer to take flags. But that's another issue.

If the bcrypt thing is not possible without another module, I would drop that part for now.

How about using the wordanalyzer (or regexanalyzer) for now and migrate to a better solution later (e.g. with flags when I implemented them)?

**Comment by d-Rickyy-b** [comment]
The bcrypt analyzer available in pastepwn matches on all possible regexes

**Comment by Zeroji** [comment]
If you want I can just add a `flags` arguments to the RegexAnalyzer while I'm at it, it's pretty straightforward!
