### ISSUE TITLE
Check paste insertion code of database adapters

### ISSUE THREAD

**Issue by d-Rickyy-b** [d-Rickyy-b/pastepwn#48]
Check if an error is thrown if a duplicate paste ID is inserted into the db (and catch it otherwise or refactor code to be an upsert).

**Comment by sharon8** [comment]
Hi @d-Rickyy-b I'd like to tackle this issue. Is there anything I should know before starting?

Thanks : )

**Comment by d-Rickyy-b** [comment]
Hi there, thanks for your interest. This issue is about creating test cases where for example duplicate pastes are inserted and how the database connectors will handle these cases.

Make sure to test what the current implementation does and in case an exception happens also make sure to either catch the exception for now or refactor the code so that instead of only inserting do an upsert of the data.

If you come across any questions, don't hesitate to contact me!

**Comment by sharon8** [comment]
Yes. Please take it. I was unable to get to it

Thanks,

**Comment by d-Rickyy-b** [comment]
@DanBenHa Sure, you can take it :) thanks for your help.

**Comment by DanBenHa** [comment]
I'm kind of new to all those databases. Which one should I best start with?

Also, is there a self-contained example as to the usage of pastepwn? I tried examples/example.py and it can connect to a local MongoDB if I remove the IP, but the script throws an error on the telegram action.
How do I provide pastebin URLs to pastepwn?

Sorry for these stupid questions...

**Comment by d-Rickyy-b** [comment]
@DanBenHa first things first: Every unit/piece of code for pastepwn is self-contained. That means that you don't need to test the integration with other code and hence you don't need to run the example.py file. That file is an example for people who want to play around with pastepwn.

That being said you can test the database connection yourself by simply setting up a mongodb (or other database) instance and create a new python file where you import the mongodb connector. Then you can simply call the contained methods with different inputs to see how the connectors behave. The task is to check if any error will be thrown or if the code correctly handles inserts for already present pastes.

PS: You get the error for the Telegram Action, because it's an example and you probably did not provide the action with a valid token. You can simply remove the action and all analyzers from the file. BUT be aware that pastepwn will still crash without a valid pastepwn pro account, so that wouldn't make sense anyway.

Ah, and never excuse yourself for any questions. You are new to this project so I bet it's not easy to wrap your mind around it. If you have any follow up questions, feel free to contact me.
