### ISSUE TITLE
Create docker-compose.yml file

### ISSUE THREAD

**Issue by d-Rickyy-b** [d-Rickyy-b/pastepwn#54]
Currently there is no (working) docker image available. The goal is to have a docker image + a docker-compose file which automatically starts a mongodb & pastepwn or a mysql & pastepwn or sqlite & pastepwn.

For that we need to read environment variables.

**Comment by trixpan** [comment]
nice idea. I would suggest the 3rd option. Will submit a PR shortly

**Comment by Selich** [comment]
I could do that, no biggy. Can you just elaborate more?
As I understand it: you just want to start a docker container when you run a pastepwn?

**Comment by d-Rickyy-b** [comment]
Hi @Selich, thanks for your interest.

I want to have a dockerfile which builds a docker container of pastepwn. I just noticed that I already created a dockerfile some time ago (check [docker hub](https://cloud.docker.com/repository/docker/0rickyy0/pastepwn/builds)). The dockerfile for that is also in the repo already.

The thing that's still missing is the docker-compose file with which you could start a database container and pastepwn.

It would be awesome to have some kind of environment variable(s) to control to which database pastepwn should connect. Currently the database connection is done by hand in the `/pastepwn/start.py` file. Since this is not a trivial task, this is optional to do.

I will rename this task to "Create docker-compose.yml file" so it reflects better what the goal of fixing this issue is.

**Comment by Selich** [comment]
Thanks, @d-Rickyy-b for the clear up.
I will start working on it and check the start.py file.
Gonna report in a few days if something comes up.

**Comment by d-Rickyy-b** [comment]
I just noticed, that there is some information missing to solve this issue:

1) There is currently no start.py file
2) The start.py file will be created by a user. They can use the [example.py](https://github.com/d-Rickyy-b/pastepwn/blob/master/examples/example.py) file to configure the pastepwn instance.
3) In the docker-compose file there must be a read-only volume mapping of the `/file/to/user/start.py` to the `/pastepwn/start.py` inside the container.

That's basically it. The docker image can be found on [Docker-Hub](https://hub.docker.com/r/0rickyy0/pastepwn) at `0rickyy0/pastepwn`.

**Comment by brandonlbarrow** [comment]
This seems to still be outstanding so I'll take a shot at it

**Comment by brandonlbarrow** [comment]
https://github.com/d-Rickyy-b/pastepwn/pull/157

**Comment by ayedaemon** [comment]
Is this still open?

**Comment by d-Rickyy-b** [comment]
Still open, @ayedaemon

**Comment by d-Rickyy-b** [comment]
Although there has been a pull request that could use a review

**Comment by d-Rickyy-b** [comment]
Closed via #157
