### ISSUE TITLE
Add possibility to force use IPv4 or IPv6

### ISSUE THREAD

**Issue by d-Rickyy-b** [d-Rickyy-b/pastepwn#57]
If there are IPv4 and v6 available, the user should be able to force use one of them.

**Comment by d-Rickyy-b** [comment]
https://stackoverflow.com/questions/33046733/force-requests-to-use-ipv4-ipv6

**Comment by grplyler** [comment]
Hi there! I am looking to contribute for Hacktoberfest 2020. Is this issue still up for grabs?

**Comment by d-Rickyy-b** [comment]
Hi @grplyler sorry for the wait. I tried to implement this behavior in https://github.com/d-Rickyy-b/pastepwn/commit/3483566870e6fd852eb462e31074817b02d67bdf - maybe you can take a quick look and if you find something to improve, I'd be glad to have a PR from you - no matter how big it is.

**Comment by d-Rickyy-b** [comment]
Implemented in dev
