### ISSUE TITLE
E-Mail action

### ISSUE THREAD

**Issue by d-Rickyy-b** [d-Rickyy-b/pastepwn#59]
There should be a possibility to send emails on certain pastes.

**Comment by d-Rickyy-b** [comment]
To add a bit more context:

To solve this issue there needs to be a new action added in the [actions directory](https://github.com/d-Rickyy-b/pastepwn/tree/master/pastepwn/actions). The action must follow the example of the other analyzers in this directory. Don't forget to add the action to the [action package file](https://github.com/d-Rickyy-b/pastepwn/blob/master/pastepwn/actions/__init__.py).

The most simple example for such an action is the [GenericAction](https://github.com/d-Rickyy-b/pastepwn/blob/master/pastepwn/actions/genericaction.py) which executes a passed function.

This action takes a username, password, receiver mail address, hostname, port and when executed sends out a an e-mail to the receiver containing the paste.

Tests are not necessary but highly appreciated. If there are questions, don't hesitate to contact me.

**Comment by aditya274** [comment]
[**Email action implementation**](https://github.com/d-Rickyy-b/pastepwn/pull/78)

**Comment by d-Rickyy-b** [comment]
I need a bit more time to check the given implementations.

**Comment by Raavtube** [comment]
What do you mean by sending emails on certain pastes? Like when the analization is done?

**Comment by d-Rickyy-b** [comment]
Hi there. This issue got already two implementations so I don't think you should invest more time into it.

You can of course check the current PRs and improve them.

**Comment by Raavtube** [comment]
Ok sounds good

Thanks,
Ryan Vogel
CEO of Start from Scratch
Contact me at info@raavcorp.com
Visit my website raavcorp.com

**Comment by d-Rickyy-b** [comment]
implemented in #78
