### ISSUE TITLE
On start method

### ISSUE THREAD

**Issue by d-Rickyy-b** [d-Rickyy-b/pastepwn#60]
There are users which would like to perform an action when pastepwn is fully initialized and running. There should be a way to register a handler for that.

**Comment by R4H33M** [comment]
I would like to take this one! :)

**Comment by d-Rickyy-b** [comment]
@R4H33M thank you :) feel free to ask any questions. I usually reply within 1-3 hours during 9-23 o'clock UTC+2.

To specify a bit more:

### Definition of done
1) There is a way to register one (or multiple) function(s) as handlers
2) That function(s) will be executed after the start() method finished
3) That function(s) will be executed within a `try: ... except:` clause
4) Errors will be logged but shall NOT stop pastepwn.

**Comment by R4H33M** [comment]
I have added this functionality: #136 
I hope it meets expectations ;)

**Comment by d-Rickyy-b** [comment]
Will take a look shortly :) thank you.

**Comment by R4H33M** [comment]
Thanks for merging! Really appreciate it! Also, maybe you forgot to close this issue??

**Comment by d-Rickyy-b** [comment]
Hi there. Yes, thanks for pointing that out. Quick tip: when you write `#fixes #60` in the commit description, then the issue will automatically be closed after the PR is merged.

Thanks for your work.
