### ISSUE TITLE
Database Connector analyzer

### ISSUE THREAD

**Issue by d-Rickyy-b** [d-Rickyy-b/pastepwn#70]
Match on database connection strings such as `mongodb://ip`

**Comment by d-Rickyy-b** [comment]
To add a bit more context:

To solve this issue there needs to be a new analyzer added in the [analyzers directory](https://github.com/d-Rickyy-b/pastepwn/tree/master/pastepwn/analyzers). The analyzer must follow the example of the other analyzers in this directory. Don't forget to add the analyzer to the [analyzer package file](https://github.com/d-Rickyy-b/pastepwn/blob/master/pastepwn/analyzers/__init__.py).

The most simple example for such an analyzer is the [AlwaysTrueAnalyzer](https://github.com/d-Rickyy-b/pastepwn/blob/master/pastepwn/analyzers/alwaystrueanalyzer.py) which always returns True.

A DatabaseConnectorAnalyzer could match on `mongodb://ip` for example. 

Tests are not necessary but highly appreciated. If there are questions, don't hesitate to contact me.

**Comment by d-Rickyy-b** [comment]
Implemented in #79 - needs some field testing with live pastebin data

**Comment by d-Rickyy-b** [comment]
I just want to test this analyzer with live pastebin data on as many pastes as possible to make sure there are no false positives ^^. Nothing special. I could close this issue and create a new one when I come across any issue.

**Comment by YellowFoxH4XOR** [comment]
Sure I will try finding  some false positive cases :)
