### ISSUE TITLE
Database Dump Analyzer

### ISSUE THREAD

**Issue by d-Rickyy-b** [d-Rickyy-b/pastepwn#72]
There should be a new analyzer to find pastes which contain a database dump.

To solve this issue there needs to be a new analyzer added in the [analyzers directory](https://github.com/d-Rickyy-b/pastepwn/tree/master/pastepwn/analyzers). The analyzer must follow the example of the other analyzers in this directory. Don't forget to add the analyzer to the [analyzer package file](https://github.com/d-Rickyy-b/pastepwn/blob/master/pastepwn/analyzers/__init__.py).

The most simple example for such an analyzer is the [AlwaysTrueAnalyzer](https://github.com/d-Rickyy-b/pastepwn/blob/master/pastepwn/analyzers/alwaystrueanalyzer.py) which always returns True.

This analyzer should match different kinds of database dumps. There are different formats for database dumps. It's up to you how many of those you want to implement. On haveibeenpwned.com there is a nice [explanation on database dumps in pastes](https://haveibeenpwned.com/Pastes) which should serve as a source for ideas.

Tests are not necessary but highly appreciated. If there are questions, don't hesitate to contact me.

**Comment by sedaboni** [comment]
#76

**Comment by trixpan** [comment]
happy to own this

**Comment by d-Rickyy-b** [comment]
Hey @trixpan you are of course free to work on this - BUT there have been two PRs already for this issue (#76 and #75). In order to prevent duplicate work I would suggest picking another issue. All issues I marked as hacktoberfest are pretty easy to implement in no longer than ~30 minutes max.

**Comment by d-Rickyy-b** [comment]
Merged #76
