### ISSUE TITLE
Email and password pair analyzer

### ISSUE THREAD

**Issue by d-Rickyy-b** [d-Rickyy-b/pastepwn#82]
There should be a new analyzer to find pastes which contain email/password pairs.

To solve this issue there needs to be a new analyzer added in the [analyzers directory](https://github.com/d-Rickyy-b/pastepwn/tree/master/pastepwn/analyzers). The analyzer must follow the example of the other analyzers in this directory. Don't forget to add the analyzer to the [analyzer package file](https://github.com/d-Rickyy-b/pastepwn/blob/master/pastepwn/analyzers/__init__.py).

The most simple example for such an analyzer is the [AlwaysTrueAnalyzer](https://github.com/d-Rickyy-b/pastepwn/blob/master/pastepwn/analyzers/alwaystrueanalyzer.py) which always returns True.

This analyzer should match email/password pairs. Check out this [example paste](https://pastebin.com/SvZR2M9L). Best would be to subclass the regex analyzer.

Tests are not necessary but highly appreciated. If there are questions, don't hesitate to contact me.

**Comment by bajubullet** [comment]
@d-Rickyy-b I would like to create a PR for this issue
