### ISSUE TITLE
Discord Action

### ISSUE THREAD

**Issue by Mxrk** [d-Rickyy-b/pastepwn#83]

**Comment by d-Rickyy-b** [comment]
It would be awesome to have a new action which sends found pastes to a discord channel.

To solve this issue there needs to be a new action added in the [actions directory](https://github.com/d-Rickyy-b/pastepwn/tree/master/pastepwn/actions). The action must follow the example of the other actions in this directory. Don't forget to add the action to the [action package file](https://github.com/d-Rickyy-b/pastepwn/blob/master/pastepwn/actions/__init__.py).

The most simple example for such an action is the [GenericAction](https://github.com/d-Rickyy-b/pastepwn/blob/master/pastepwn/actions/genericaction.py) which executes a passed function.

The action must be able to send a new message to a discord channel. The bot does not need to react on any command. It would be super awesome if your implementation would support templating as implemented in the [Telegram Action](https://github.com/d-Rickyy-b/pastepwn/blob/641afb3174c999a2f8a18d522791227a3a3b8189/pastepwn/actions/telegramaction.py#L32-L37).

Tests are not necessary but highly appreciated. If there are questions, don't hesitate to contact me.

**Comment by dynomite567** [comment]
I would love to tackle this issue. Let me at it!

**Comment by d-Rickyy-b** [comment]
Hey @dynomite567, thanks a lot for your interest. I am not sure if @Mxrk was about to implement this. Just to make sure to avoid double work.

In case @Mxrk is working on it, you could create a PR if you find something that should be changed in his code.

**Comment by d-Rickyy-b** [comment]
There are 2 ways on how to post messages to discord:
1) [Webhooks](https://discordapp.com/developers/docs/resources/webhook#execute-webhook)
2) Via a bot

Best would be to have both ways available.

**Comment by Mxrk** [comment]
@dynomite567 Hey, you can still add the other way to send messages to a channel (or user). I only did the webhook way.

**Comment by dynomite567** [comment]
So, I can see how to do this one to two ways. One, I can create a whole another action file named DiscordBotAction.py and create the whole function there and also (possibly) rename the current DiscordAction.py to something like DiscordWebhookAction.py or something shorter. The other option is for me to figure out a way to implement the bot functions into one DiscordAction.py, however it may complicate things for me and might have a possiblity of not working, however I could do it. I want to know which one you guys prefer before I move on.

Both methods however require discord.py as a dependency to implement, and will be added to the requirements.txt in my PR once finished.

**Comment by d-Rickyy-b** [comment]
If it's too stuffed, put it into another file otherwise you could use the same file if there is not much code.

Maybe you can check out the following gist. Should be easy to implement I think. And no requirements needed. But I only had a quick look so not sure if that fits well.

https://gist.github.com/ianklatzco/769d9e3a991dc2f443a2e105b0157117

**Comment by dynomite567** [comment]
Seems like it still needs some way to connect to a web socket on first run, so it looks like discord.py might still be required for that function. Regardless, I was able to fit everything onto one file, and I should have a PR ready for review if you want to look.

**Comment by Zeroji** [comment]
Hi,

I might have found a way to make it work without the requirement for discord.py (which keeps the 3.4 compatibility), I'm making a PR right now forked off Mxrk's commits (I hope doing it this way can work)
