### ISSUE TITLE
Phone number analyzer

### ISSUE THREAD

**Issue by d-Rickyy-b** [d-Rickyy-b/pastepwn#90]
There should be a new analyzer to find pastes which contain phone numbers.

To solve this issue there needs to be a new analyzer added in the [analyzers directory](https://github.com/d-Rickyy-b/pastepwn/tree/master/pastepwn/analyzers). The analyzer must follow the example of the other analyzers in this directory. Don't forget to add the analyzer to the [analyzer package file](https://github.com/d-Rickyy-b/pastepwn/blob/master/pastepwn/analyzers/__init__.py).

The most simple example for such an analyzer is the [AlwaysTrueAnalyzer](https://github.com/d-Rickyy-b/pastepwn/blob/master/pastepwn/analyzers/alwaystrueanalyzer.py) which always returns True.

This analyzer should match phone numbers in the international format. Best would be to subclass the regex analyzer and create a regex to detect phone numbers. Make sure to also detect whitespace separated country codes with `\s*`. Also please check if the country codes and lengths are valid for a phone number.

Tests are not necessary but highly appreciated. If there are questions, don't hesitate to contact me.

**Comment by dmoneyballer** [comment]
This seems easy enough, I'll take a crack at it

**Comment by d-Rickyy-b** [comment]
Hey @dmoneyballer - before you start, please check #91 - someone started work on it already. I just want to avoid duplicate work.

Thanks for your interest :)

**Comment by dmoneyballer** [comment]
Thanks for the heads up

**Comment by qkniep** [comment]
I created pull request #94 to improve upon #91 and also add test cases to verify.
