### ISSUE TITLE
Add PastebinScraper by default, since it's currently the only scraper

### ISSUE THREAD

**Issue by d-Rickyy-b** [d-Rickyy-b/pastepwn#92]
When the `scraping_handler.scrapers` list is empty and the start method (see below) is being called, a new instance of PastebinScraper should be initialized and added via `self.add_scraper(PastebinScraper)` in line 97.

https://github.com/d-Rickyy-b/pastepwn/blob/641afb3174c999a2f8a18d522791227a3a3b8189/pastepwn/core/pastepwn.py#L92-L100

**Comment by Samyak2** [comment]
I would like to work on this.
