### ISSUE TITLE
Steam key analyzer

### ISSUE THREAD

**Issue by d-Rickyy-b** [d-Rickyy-b/pastepwn#96]
There should be a new analyzer to find pastes which contain Steam keys. I don't expect this task to take more than 30 minutes to implement.

To solve this issue there needs to be a new analyzer added in the [analyzers directory](https://github.com/d-Rickyy-b/pastepwn/tree/master/pastepwn/analyzers). The analyzer must follow the example of the other analyzers in this directory. Don't forget to add the analyzer to the [analyzer package file](https://github.com/d-Rickyy-b/pastepwn/blob/master/pastepwn/analyzers/__init__.py).

The most simple example for such an analyzer is the [AlwaysTrueAnalyzer](https://github.com/d-Rickyy-b/pastepwn/blob/master/pastepwn/analyzers/alwaystrueanalyzer.py) which always returns True.

This analyzer should match any possible steam key. An example paste can be found [here](https://pastebin.com/A7Uevwma).

I expect unit tests to check if the analyzer works as intended. If there are questions, don't hesitate to contact me.

**Comment by mikek2** [comment]
I'm interested in getting this one.

Just one thing to clarify about the example of steam keys provided - is it sufficient to create a regex to check the first half of the paste? (just the serial number, as opposed to the serial and game name)

**Comment by d-Rickyy-b** [comment]
Hi there :) sure, I will assign you right away.

It's sufficient to create a new analyzer subclassing RegexAnalyzer and creating a simple regex for the game key. Should not be too hard. The game name is not important.
