### ISSUE TITLE
Epic Games key analyzer

### ISSUE THREAD

**Issue by d-Rickyy-b** [d-Rickyy-b/pastepwn#97]
There should be a new analyzer to find pastes which contain 'Epic Games' keys. I don't expect this task to take more than 30 minutes to implement.

To solve this issue there needs to be a new analyzer added in the [analyzers directory](https://github.com/d-Rickyy-b/pastepwn/tree/master/pastepwn/analyzers). The analyzer must follow the example of the other analyzers in this directory. Don't forget to add the analyzer to the [analyzer package file](https://github.com/d-Rickyy-b/pastepwn/blob/master/pastepwn/analyzers/__init__.py).

The most simple example for such an analyzer is the [AlwaysTrueAnalyzer](https://github.com/d-Rickyy-b/pastepwn/blob/master/pastepwn/analyzers/alwaystrueanalyzer.py) which always returns True.

This analyzer should match any possible 'Epic Games' key. An example for the key format is `K5XSH-CTLEQ-Q5RF6-U7YD9`. The easiest solution would be to extend the [RegexAnalyzer](https://github.com/d-Rickyy-b/pastepwn/blob/master/pastepwn/analyzers/regexanalyzer.py).

I expect unit tests to check if the analyzer works as intended. If there are questions, don't hesitate to contact me.

**Comment by lringham** [comment]
Hey, can I be assigned to this issue?

**Comment by d-Rickyy-b** [comment]
@lringham Sure, now you are :) thanks for helping.

**Comment by lringham** [comment]
Hey Ricky, 

Which folder should contain the unit tests?

**Comment by d-Rickyy-b** [comment]
Hi there. In the analyzers directory there is a tests folder. There are examples of other tests already.

**Comment by synackray** [comment]
I created #118 with the base requirements. If there are additional keys to compare against, the regex can be adjusted to not match against illegal characters.
