### ISSUE TITLE
Create unit test for PastebinURLAnalyzer

### ISSUE THREAD

**Issue by d-Rickyy-b** [d-Rickyy-b/pastepwn#99]
The current implementation of the [PastebinURLAnalyzer](https://github.com/d-Rickyy-b/pastepwn/blob/master/pastepwn/analyzers/pastebinurlanalyzer.py) did not get any unit tests yet. This should change now.

To resolve this task you need to create a new unit test file in the [tests directory](https://github.com/d-Rickyy-b/pastepwn/tree/master/pastepwn/analyzers/tests) named `pastebinurlanalyzer_test.py`.

In this file implement at least 5 positive and 5 negative tests. The more the better!
Make sure to test tricky combinations. Unit tests should really be testing code to its limits.

PS: It's okay when tests make the build fail because the code is faulty! (It's not okay if tests fail for no valid reason)

**Comment by palaparthi** [comment]
I can take this up

**Comment by palaparthi** [comment]
There is no start.py? Was wondering how to run the project

**Comment by d-Rickyy-b** [comment]
You would need to copy the example.py from the examples directory. But that will only work when you got a pastebin pro account.

Better to run the unit tests independently with `python -m unittest discover -s . -v -p "*_test.py"`

**Comment by palaparthi** [comment]
Just to be clear is www.pastebin.com/something or pastebin.com/something considered a valid pastebin url?

**Comment by d-Rickyy-b** [comment]
Since there were no unit tests yet it is possible that the current implementation is broken or faulty.

Only pastebin.com/something with http and https prefixed is a valid url.

It is okay when tests fail because of coding errors in pastepwn. That's what tests are for right? :blush:

**Comment by d-Rickyy-b** [comment]
Fixed in 88abf882aecb1e5c1a92ea4d9b868d02d37de687
